[package]
name = "experiments"
description = "Let's Experiment with Rust Internals!"
version = "0.1.0"
authors = ["stevej@fruitless.org"]
license = "Apache-2.0"
repository = "https://github.com/stevej/rust-experiments"

[dependencies]
